### ISSUE TITLE
Add loading animation when switching sections

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#47] opened 2017-01-16 21:20 UTC

**Comment by matthova** [comment] 2017-01-29 19:50
Is this a duplicate of [#33](https://github.com/e-nable/Limbforge/issues/33) or an additional place where an animation could go?

**Comment by kaitlynhova** [comment] 2017-03-03 20:14
closing and adding to [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out

**Closed as completed by kaitlynhova** 2017-03-03 20:14 UTC
Labels: enhancement
